### ISSUE TITLE
Problem Implementing

### ISSUE THREAD

**Issue by leopoldjoy** [ms88privat/example-multiple-swipe-cards#1]
Hello @ms88privat,

I realize you probably haven't gotten a chance to write documentation for this module, but I have tried to implement it using the "quick start" instruction documentation for [react-native-tinder-swipe-cards](https://github.com/meteor-factory/react-native-tinder-swipe-cards) however so far I cannot get the module to work. How would the implementation vary from that?

This is my current code that is not working:

```
import SwipeCards from 'react-native-multiple-swipe-cards';

const cards = [
  {text: 'Tomato', backgroundColor: 'red'},
  {text: 'Aubergine', backgroundColor: 'purple'},
  {text: 'Courgette', backgroundColor: 'green'},
  {text: 'Blueberry', backgroundColor: 'blue'},
  {text: 'Umm...', backgroundColor: 'cyan'},
  {text: 'orange', backgroundColor: 'orange'},
]

const Card = props => (
  <View style={[styles.card, {backgroundColor: props.backgroundColor}]}>
    <Text>{props.text}</Text>
  </View>
);

const NoMoreCards = () => (
  <View style={styles.noMoreCards}>
    <Text>No more cards</Text>
  </View>
);

class Area extends Component {
  handleYup (card) {
    console.log(`Yup for ${card.text}`)
  }
  handleNope (card) {
    console.log(`Nope for ${card.text}`)
  }
  render() {
    <SwipeCards
      cards={cards}

      renderCard={(cardData) => <Card {...cardData} />}
      renderNoMoreCards={() => <NoMoreCards />}

      handleYup={this.handleYup}
      handleNope={this.handleNope}
    />
  }
}
```

Thank you!

**Comment by leopoldjoy** [comment]
Nevermind, realized there's a great example inside of this repo. Don't know how I missed that.

**Comment by ms88privat** [comment]
@leopoldjoy Hi again, I'm going to write the documentation in the next couple of days. There is also a feature to trigger Yup or Nope with a button click.

**Comment by leopoldjoy** [comment]
@ms88privat thanks for the response. I look forward to the documentation as controlling Yup or Nope with a button click would be really useful to me. Thanks again for the awesome module! :)

**Comment by ms88privat** [comment]
For the button clicks trigger one of these functions:

``` js
handleTriggerNope() {
    this._SwipeCardsRef.onRelease(null, {vx: -1.5, vy: 0.5, isPopCard: true});
  }

  handleTriggerYup() {
    this._SwipeCardsRef.onRelease(null, {vx: 1.5, vy: 0.5, isPopCard: true});
  }
```

``` js
<SwipeCards
        ref={(c) => this._SwipeCardsRef = c}
        cards={this.props.cards}
        onPress={this.handlePressCard}
        onYup={this.handleYup}
        onNope={this.handleNope}
        renderCard={this.renderCard}
        renderNoCards={this.renderNoCards}
      />
```

**Comment by leopoldjoy** [comment]
@ms88privat Sorry, missed this. Closing #2.

**Comment by leopoldjoy** [comment]
@ms88privat Is there any way I can control the speed of the animation? It seems to be so fast that sometimes it's hard to notice it animated away. Thank you!!

**Comment by leopoldjoy** [comment]
@ms88privat Additionally, is there any way to run a callback after the animation is complete? (After the `.onRelease()` function runs). Thanks again!

**Comment by ms88privat** [comment]
@leopoldjoy sorry for the late reply. You can control the speed by adjusting the values of `vx` and `vy`. Did you use exactly the values i specified above? They are working fine for me. The callback for onRelease is `onYup` and onNope`? Can you please clarify your question?

**Comment by leopoldjoy** [comment]
@ms88privat Adjusting the values solved the problem for me in the end. Thank you!!
